services:
  # Development service for local development
  runalyze-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: runalyze-mcp-dev
    ports:
      - "8081:8080"
    environment:
      - RUNALYZE_BASE_URL=https://runalyze.com/api/v1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

networks:
  default:
    name: runalyze-mcp-network 