version: '3.8'

services:
  runalyze-mcp:
    image: ghcr.io/philosowaffle/runalyze-mcp:latest
    container_name: runalyze-mcp
    ports:
      - "8080:8080"
    environment:
      - RUNALYZE_BASE_URL=https://runalyze.com/api/v1
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: runalyze-mcp-network 