version: '3.8'

services:
  runalyze-mcp:
    image: ghcr.io/philosowaffle/runalyze-mcp:latest
    container_name: runalyze-mcp
    ports:
      - "8080:8080"
    environment:
      - RUNALYZE_BASE_URL=https://runalyze.com/api/v1
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  runalyze-mcp-dev:
    build: .
    container_name: runalyze-mcp-dev
    ports:
      - "8081:8080"
    environment:
      - RUNALYZE_BASE_URL=https://runalyze.com/api/v1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./RunalyzeMcp:/app/RunalyzeMcp:ro
      - ./RunalyzeMcp.Tests:/app/RunalyzeMcp.Tests:ro
    restart: unless-stopped
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=runalyze-mcp"
      - "com.docker.compose.service=runalyze-mcp-dev"

networks:
  default:
    name: runalyze-mcp-network 